<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PhysicaStudio.Document/PhysicaStudio.Document.csproj" />
    <ProjectReference Include="../PhysicaStudio.Observables/PhysicaStudio.Observables.csproj" />
  </ItemGroup>
</Project>

